doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            project_project_id: 'App\Model\Project\Entity\Project\IdType'
            project_table_id: 'App\Model\Project\Entity\Table\IdType'

            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Project:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Project/Entity'
                prefix: 'App\Model\Project\Entity'
                alias: Project
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User